### ISSUE TITLE
Invalid "latest-version" and "lastest-commit" (sic)

### ISSUE THREAD

**Issue by brjdev** [cgruver/okd-jenkins-pipeline#2]
The docker image fully built, but the following apply failed with invalid "latest-version" and "lastest-commit" (sic)

ERROR: apply returned an error;
{reference={/home/build/workspace/ben-pipeline/ben-pipeline-basic-ocp-app-pipeline/apply2505283868983675515.markup={"metadata":{"generation":1,"uid":"f799beea-687a-11ea-9bf0-5254003d291c","resourceVersion":"52066858","creationTimestamp":"2020-03-17T18:13:13Z","name":"basic-ocp-app","namespace":"ben-pipeline","labels":{"app":"basic-ocp-app","template.openshift.io/template-instance-owner":"f790fb9e-687a-11ea-a6dd-525400606c1d","com.odfl.architecture.reference-models.basic-ocp-app.lastest_commit":"d066a79","com.odfl.architecture.reference-models.basic-ocp-app.committer_name":null,"com.odfl.architecture.reference-models.basic-ocp-app.author":"Jenkins","com.odfl.architecture.reference-models.basic-ocp-app.latest_version":"1.0.0-SNAPSHOT","com.odfl.architecture.reference-models.basic-ocp-app.committer_email":null},"selfLink":"/apis/image.openshift.io/v1/namespaces/ben-pipeline/imagestreams/basic-ocp-app"},"apiVersion":"image.openshift.io/v1","kind":"ImageStream","spec":{"lookupPolicy":{"local":false}},"status":{"dockerImageRepository":"docker-registry.default.svc:5000/ben-pipeline/basic-ocp-app","tags":[{"items":[{"generation":1,"image":"sha256:199f9ebb095d43cbea54d08be2fc0cc92df0416349e87f8664cceb20217c9b87","created":"2020-03-17T20:16:03Z","dockerImageReference":"docker-registry.default.svc:5000/ben-pipeline/basic-ocp-app@sha256:199f9ebb095d43cbea54d08be2fc0cc92df0416349e87f8664cceb20217c9b87"}],"tag":"latest"}]}}}, err=Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
The ImageStream "basic-ocp-app" is invalid: 
* metadata.labels: Invalid value: "com.odfl.architecture.reference-models.basic-ocp-app.latest_version": name part must be no more than 63 characters
* metadata.labels: Invalid value: "com.odfl.architecture.reference-models.basic-ocp-app.lastest_commit": name part must be no more than 63 characters
, verb=apply, cmd=oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=ben-pipeline --token=XXXXX apply -f /home/build/workspace/ben-pipeline/ben-pipeline-basic-ocp-app-pipeline/apply2505283868983675515.markup -o=name , out=, status=1}

**Comment by cgruver** [comment]
Those metadata elements are not strictly necessary.  It looks like you've got a long groupId.  It's exceeding some limit on container labels.  I'll modify the labels that get written to accommodate long groupId/artifactId combinations.

**Comment by brjdev** [comment]
The labels were removed and now build functions properly.
